# Generated by Django 3.1.4 on 2021-01-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='address',
            field=models.TextField(default='NULL'),
        ),
    ]
