# Generated by Django 3.1.4 on 2021-01-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_userprofileinfo_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='address',
            field=models.CharField(max_length=500),
        ),
    ]
